export const rentals = [
    {
        id: 1,
        title: 'City Tours In Europe, Paris',
        city: 'ternopil',
        street: 'this is streat',
        category: 'house',
        image: 'http://wahabali.com/work/travelu/images/tours/img-01.jpg',
        datailimage: 'http://wahabali.com/work/travelu/images/slider/img-01.jpg',
        betrooms: 9,
        guests: 2,
        description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh...',
        dailyRate: 23,
        shared: true,
        createdAt: '23/04/18'
    },
    {
        id: 2,
        title: 'Best of Canada Tours and Travel',
        city: 'ternopil',
        street: 'this is streat',
        category: 'combo',
        image: 'http://wahabali.com/work/travelu/images/tours/img-04.jpg',
        datailimage: 'http://wahabali.com/work/travelu/images/slider/img-02.jpg',
        betrooms: 9,
        guests: 2,
        description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh...',
        dailyRate: 56,
        shared: false,
        createdAt: '24/04/18'
    },
    {
        id: 3,
        title: 'Italy – 3 Days in Rome, Golden Gate',
        city: 'ternopil',
        street: 'this is streat',
        category: 'apartment',
        image: 'http://wahabali.com/work/travelu/images/tours/img-02.jpg',
        datailimage: 'http://wahabali.com/work/travelu/images/slider/img-03.jpg',
        betrooms: 9,
        guests: 2,
        description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh...',
        dailyRate: 223,
        shared: true,
        createdAt: '25/04/18'
    },
];