export const FETCH_RENTAL_BY_ID = 'FETCH_RENTAL_BY_ID';
export const DELETE_SINGLE_RENTAL = 'DELETE_SINGLE_RENTAL';
export const FETCH_ALL_RENTALS = 'FETCH_ALL_RENTALS';
export const GET_ERRORS = 'GET_ERRORS';